### ISSUE TITLE
fix(firmware): bb_ui_settings.c missing cwd_name arg — broken build on main

### ISSUE THREAD

**Issue by zhoushoujianwork** [daboluocc/bbclaw#35]
## Bug

Commit fb36993 (#30 CWD Pool) changed `bb_agent_create_session` from 4 params to 5 (added `cwd_name`), but missed updating the call site in `firmware/src/bb_ui_settings.c:385`.

Current main does not compile.

## Fix

One-line change in `firmware/src/bb_ui_settings.c` line 385:

```c
// Before (broken):
esp_err_t create_err = bb_agent_create_session(driver, NULL, new_sid, sizeof(new_sid));

// After (fixed — pass NULL for cwd_name):
esp_err_t create_err = bb_agent_create_session(driver, NULL, NULL, new_sid, sizeof(new_sid));
```

No other call sites are affected (`bb_ui_agent_chat.c` already uses the 5-arg form correctly).

## Verification

```bash
cd firmware && make build
```

Should compile cleanly after the fix.

## Related

- Introduced by: PR #33 / commit fb36993
- Parent issue: #30

**Comment by zhoushoujianwork** [comment]
## 🏷️ ClawFlow Triage

Classified as **bug**.

**Reason:** The body explicitly describes a broken build on main caused by a missing argument at a call site introduced by a prior commit, matching the "doesn't compile / regression since X" signal.

The matching evaluator (`evaluate-bug`) will run on the next `clawflow run` pass and post a structured assessment.

**Comment by zhoushoujianwork** [comment]
## 🔍 ClawFlow Bug Evaluation

**Reproducibility:** 10/10 — The bug is a compile error on main. Any `make build` in `firmware/` will fail deterministically. Steps are trivial: clone, build.
**Root cause:** 10/10 — Exact file, line number, and missing argument are identified. The header declares 5 params (`driver, title, cwd_name, out_sid, out_sid_len`), but `bb_ui_settings.c:385` passes only 4 (missing `cwd_name`). Confirmed by reading the source.
**Fix difficulty:** 10/10 — Single-line change: insert `NULL` as the third argument. No design decisions, no side effects, no tests to update.

**Confidence:** 10.0/10 ✅ above threshold

### Repro steps

1. `cd ~/github/bbclaw/firmware`
2. `make build`
3. Observe compiler error: `too few arguments to function 'bb_agent_create_session'` at `src/bb_ui_settings.c:385`

### Root cause analysis

Issue #30 (CWD Pool, PR #33, commit fb36993) added a `cwd_name` parameter to `bb_agent_create_session`, changing its signature from 4 to 5 parameters. The call site in `bb_ui_agent_chat.c` was updated, but the call site in `bb_ui_settings.c:385` was missed. This is the only remaining broken call site (confirmed via grep).

Note: Issue #34 (closed) is an exact duplicate filed in Chinese with the same diagnosis. It was closed without a merged PR, so the fix has not been applied yet.

### Suggested fix

In `firmware/src/bb_ui_settings.c` line 385, add `NULL` for the `cwd_name` parameter:

```c
// Before:
esp_err_t create_err = bb_agent_create_session(driver, NULL, new_sid, sizeof(new_sid));

// After:
esp_err_t create_err = bb_agent_create_session(driver, NULL, NULL, new_sid, sizeof(new_sid));
```

Verify with `cd firmware && make build`.

---

👉 If this plan looks right, add the `ready-for-agent` label to kick off automatic implementation.

**Comment by zhoushoujianwork** [comment]
## ✅ ClawFlow fix complete

**PR:** https://github.com/daboluocc/bbclaw/pull/36
**Branch:** `fix/issue-35`
**Files changed:** `firmware/src/bb_ui_settings.c`

Added the missing `NULL` for `cwd_name` as the third argument to `bb_agent_create_session` at line 385, restoring the call to match the 5-param signature introduced in commit fb36993.
